### PR TITLE
Css split

### PR DESCRIPTION
**Pull request by curtisbarnard**
# Description
- Resolves *#issue_number*
- Split the CSS that is specific to the Partners and Sponsors section into a separate SCSS file. Also refactored the media queries in main.scss a bit.

# Type of changes
- [ ] Bug fix
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

**Comment by curtisbarnard** [comment]
@kgottfri can you take a quick look at this and see if it looks right per our discussion about splitting the styling files out? Let me know and I'll merge it.

**Review by kgottfri — CHANGES_REQUESTED** [review]
The branch is currently set to merge into master, switch it to redesign_test.  It also contains every commit from redesign_test.  I'm not sure if changing the destination branch will remove all those commits in common, but if it does not, we'll want to rebase this branch and remove those commits before merging.

**Comment by curtisbarnard** [comment]
Doh! Thanks for pointing that out. Seems to have removed all the other commits.

**Comment by kgottfri** [comment]
Feel free to merge

**Pull request merged**
