### PR TITLE
Font update

### LINKED ISSUE #90: Font update
After testing the redesign_branch I found the font to be wrong. Need to update it to Monserrat.

### PR DESCRIPTION
**Pull request by curtisbarnard**
# Description
- Resolves #90 
- Update font family to Montserrat for the whole site. Updated font weights to match Figma design.

# Type of changes
- [ ] Bug fix
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

# Screenshots (optional)
image

### CODE REVIEW

**Comment by curtisbarnard** [comment]
@kgottfri can you take a quick glance at this and let me know if it looks cool to merge?

**Comment by kgottfri** [comment]
looks like the font update caused alignment issues on the logo, the top half of the logo stretches out past the bottom half now.
Screen Shot 2022-04-13 at 6 41 21 PM

**Comment by curtisbarnard** [comment]
@kgottfri I think I got the logo sorted, both in size and font weight. I also removed some redundant code related to it in the styling sheets. 
image

**Comment by kgottfri** [comment]
Perfect. Looks great. Feel free to push

**Pull request merged**
